<?php
function atomyx_portal_block_info() {
	$blocks['atomyxhelp'] = array(
		'info'   => t('Atomyx help block'), //The name that will appear in the block list.
		'cache'  => DRUPAL_NO_CACHE, //Disable cacheen
		'region' => 'content',
		'pages'  =>  'Jobs',
		'visibility' => BLOCK_VISIBILITY_LISTED,  
		'status' => 1,
		'weight' => -30,
	);

	$blocks['her2'] = array(
		'info' => t('HER2'),
		'cache' => DRUPAL_CACHE_PER_ROLE, // default
	);

	$blocks['wellcome'] = array(
		'info'   => t('wellcome'), //The name that will appear in the block list.
		'cache'  => DRUPAL_NO_CACHE, //Disable cache
		'region' => 'content',
		'pages'  =>  'Wellcome',
		'visibility' => BLOCK_VISIBILITY_LISTED,  
		'status' => 1,
		'weight' => -30,
	);

	return $blocks;
}

function atomyx_portal_block_configure($delta = '') {
  $form = array();
  if ($delta == 'atomyxhelp') {
    $form['atomyxhelp_string'] = array(
      '#type' => 'textfield',
      '#title' => t('Block contents'),
      '#size' => 60,
      '#description' => t('This text will appear in the atomyxhelp block.'),
      '#default_value' => variable_get('atomyxhelp_example_string',  t('Some example content.')),
    );
  }
  return $form;
}

function atomyx_portal_block_save($delta = '', $edit = array()) {
  if ($delta == 'atomyxhelp') {
    variable_set('atomyxhelp_example_string', $edit['atomyxhelp_string']);
  }
  return;
}


function atomyx_portal_block_view($hui = "") {
	switch($hui) {
		case "atomyxhelp" : 
			$block['subject'] = t('Title of second block (example_empty)');
			$block['content'] = variable_get('atomyxhelp_example_string',  t('Some example content.'));
			break;
		case "her2" : 
			$block['subject'] = t('Title of second block (example_empty)');
			$block['content'] = "Ёбаный второй блок";
			break;
		case "wellcome":
			$block['subject'] = t('Title of Wellcome block');
			$block['content'] = t('content wellcome');
		break;
	}
	
	return $block;
}
